### ISSUE TITLE
点击分享链接不显示内容

### ISSUE THREAD

**Issue by oxygensohn** [ialley-workshop-open/uni-halo#11]
点击分享链接不显示内容，分享朋友圈的链接同样不显示内容。

**Comment by xgr5202** [comment]
我也遇到了类似的问题，这是出现的报错信息，版本是最新的版本。
![分享](https://github.com/user-attachments/assets/6052f348-2a14-4937-a0cd-6106ac1608db)
![错误](https://github.com/user-attachments/assets/cb877cf2-c2d2-4988-b909-4cd8a56524f3)
