### ISSUE TITLE
样式更新建议

### ISSUE THREAD

**Issue by xgr5202** [ialley-workshop-open/uni-halo#12]
这是我在作者用户推荐页面发现的一个用户叫（芈亓日记），我觉得他这个样式很好看作者后面能增添类似的的样式选择吗，但是我只是个人建议一下。
![样式1](https://github.com/user-attachments/assets/3489d55e-7489-454d-9697-b2152af9046e)
![样式2](https://github.com/user-attachments/assets/9dcf5b40-7b52-4088-99fd-fd9a2d16e098)
![样式3](https://github.com/user-attachments/assets/8a78e355-1001-4209-bcec-2b00df3230ee)
![样式4](https://github.com/user-attachments/assets/de1abc4e-918a-4ecc-9d6f-936c7e102fcc)

**Comment by okay-xiaomo** [comment]
这个其实是1.0版本的样式

**Comment by xgr5202** [comment]
> 这个其实是1.0版本的样式

啊？这我属实没想到😂
