### ISSUE TITLE
【BUG】小程序真机调试页面加载问题

### ISSUE THREAD

**Issue by zhynxq** [ialley-workshop-open/uni-halo#16]
![](http://gcore.jsdelivr.net/gh/zhynxq/photo/issue2.jpg)
![](http://gcore.jsdelivr.net/gh/zhynxq/photo/issue1.png)

**Comment by okay-xiaomo** [comment]
我没有复现！

**Comment by liujiaxian** [comment]
@zhynxq 我也是这个问题，解决了吗？

**Comment by zhynxq** [comment]
暂时没有






我的宝藏女孩?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ialley-workshop-open/uni-halo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月14日(星期四) 晚上9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ialley-workshop-open/uni-halo] 小程序真机调试页面加载问题 (Issue #16)





 
@zhynxq 我也是这个问题，解决了吗？

**Comment by okay-xiaomo** [comment]
@zhynxq @liujiaxian 

我这边都正常的 
![image](https://github.com/user-attachments/assets/6c572668-97f3-4424-81ac-6d970845f773)
![2c92ca647f0b4a9ef664b7623515ad3a_720](https://github.com/user-attachments/assets/316c5615-503b-4bed-8736-5e4e7902608a)

**Comment by liujiaxian** [comment]
我发现token删掉了小程序客户端也能获取接口数据，但是真机就是不行，所以怀疑是获取接口授权有问题拿不到数据。
<img width="1161" alt="image" src="https://github.com/user-attachments/assets/a8adf210-22b7-486b-814e-f19b9ce3892c">
![image](https://github.com/user-attachments/assets/9b4fc096-6911-4e1f-9737-a301d573f534)

**Comment by okay-xiaomo** [comment]
奇怪的问题，主要是我没有能复现

**Comment by zhynxq** [comment]
我找到原因了，应该是ssl证书的问题，我是用的是自签证书，但是小程序要求比较严格。证书修改之后就没有问题了。
![9](https://github.com/user-attachments/assets/8f3e43bd-4e6a-43f5-9c3a-a384f61e3dc8)


> 奇怪的问题，主要是我没有能复现

**Comment by okay-xiaomo** [comment]
### 1、体验版预览异常
将体验页面设置为 `pages/index/index` 
![image](https://github.com/user-attachments/assets/8ef15a4a-060d-47f4-a72c-eb9514a39690)

### 2、真机调试异常
尝试清除日志和存储，然后重启当前页面
![77d58040dc8aaf083443f3f8e14930ff](https://github.com/user-attachments/assets/a47eda85-c0cd-462c-abf2-e92a96300676)
