### ISSUE TITLE
一键开启审核模式（关于分类页面不显示建议）

### ISSUE THREAD

**Issue by xgr5202** [ialley-workshop-open/uni-halo#18]
目前就我自己审核遇到的问题，如果你隐藏了文章的显示，但是分类页面还是会显示具体分类，无法单独屏蔽分类的相关具体分类，但是你屏蔽文章显示之后，对应的分类就没有文章显示了，审核就会驳回，显示你必须要有对应的内容。（所以建议审核模式直接不显示分类这个栏目）
![小程序 - Google Chrome-2024-10-18_12-09-22](https://github.com/user-attachments/assets/d2761749-1eaf-4f1c-8480-d2b01e54c588)

**Comment by okay-xiaomo** [comment]
目前审核模式 分类页面显示一句话。

**Comment by okay-xiaomo** [comment]
当前审核模式支持自定义模拟数据。
