### ISSUE TITLE
首页页面精品分类后台插件无法进行关闭，只能默认打开

### ISSUE THREAD

**Issue by xgr5202** [ialley-workshop-open/uni-halo#19]
![shouye](https://github.com/user-attachments/assets/f6606678-6c14-4b6d-bf32-044186711a0e)
我在后台插件进行了精品分类展示的关闭，但是还是显示了精品分类
![fenlei](https://github.com/user-attachments/assets/c111a1d7-a2d2-4c41-ae79-f0a1719994bc)

**Comment by okay-xiaomo** [comment]
已修复
