### ISSUE TITLE
恋爱日记设置了爱心图片但是不显示

### ISSUE THREAD

**Issue by xgr5202** [ialley-workshop-open/uni-halo#20]
![riji](https://github.com/user-attachments/assets/0889bda8-10b2-473d-ac84-6f322c6f0889)
![插件详情 - 南枝已谢 - Google Chrome-2024-10-18_13-11-59](https://github.com/user-attachments/assets/573a8823-f736-48d1-9567-610b0e38f567)

**Comment by okay-xiaomo** [comment]
图片地址放到浏览器正常访问吗？

**Comment by xgr5202** [comment]
> 图片地址已发布浏览器正常访问吗？

图片可以正常访问。

**Comment by xgr5202** [comment]
> 图片地址已发布浏览器正常访问吗？

图片浏览器是可以正常访问的。

**Comment by okay-xiaomo** [comment]
已修复
