### ISSUE TITLE
📳 案例征集

### ISSUE THREAD

**Issue by okay-xiaomo** [ialley-workshop-open/uni-halo#23]
大家好，  

为了提供更好的开发体验和技术支持，我们希望各路大佬们能一起贡献优秀的 Demo 与案例，让 uni-halo 更加完善。
 
对于各位大佬们的提交，我们会保持跟进与回复，采纳后的项目将在 README 的重要位置展示，感谢你的支持！

---

#### 格式如下：

- 作者 / 站长：可选
- 作者的站点：可选
- 小程序名称：必须 
- 小程序太阳码：必须

---

#### 示例如下：

- 作者 / 站长：小莫唐尼
- 作者的站点：https://www.xiaoxiaomo.cn/
- 小程序名称：小莫唐尼 
- 小程序太阳码：

<img width="344" height="344" alt="Image" src="https://github.com/user-attachments/assets/5ca1f4a9-98df-416a-8d00-800d4bd00abf" />

**Comment by Dominic-KK** [comment]
- 作者 / 站长：Dominic
- 作者的站点：https://www.dominickk.top/
- 小程序名称：Dominic CodeNotes
- 小程序太阳码：
![Image](https://github.com/user-attachments/assets/5300b5bd-2b28-4a2c-ae71-ec7c1c7b65aa)

**Comment by suble** [comment]
作者 / 站长：yusuble
[作者的站点：[](https://blog.suble.cn/)
小程序名称：yusuble特效
小程序太阳码：

![Image](https://github.com/user-attachments/assets/87d7bfd8-d593-4c2f-8b79-9d78a28ad689)
