### ISSUE TITLE
支持隐藏精选分类

### ISSUE THREAD

**Issue by cooker** [ialley-workshop-open/uni-halo#9]
<img width="352" alt="image" src="https://github.com/ialley-workshop-open/uni-halo/assets/10859254/3f233720-98c2-4506-a99d-df6b0e8feae3">

1. 小程序审核，需隐藏精选分类
2. Halo 设置分类不显示，但是小程序还是显示。导致小程序审核不通过

**Comment by okay-xiaomo** [comment]
下个版本支持，欢迎提供更多的配置内容。

**Comment by okay-xiaomo** [comment]
已支持！
